name: py_gpu_segment

channels:
  - pytorch
  - nvidia
  - rapidsai
  - conda-forge

dependencies:
  - python=3.10
  - numpy=1.26.4
  - cuda-version=12.2
  - cuda-cudart
  - pytorch-cuda=12.4
  - rapids=24.12
  - pytorch=2.4.0
  - torchvision
  - torchaudio
  - albumentations=2.0.2
  - torchmetrics
  - tensorboard
  - pytorch-ignite
  - jupyterlab
  - xarray-spatial
  - geopandas
  - panel
  - matplotlib-base
  - scikit-learn
  - scikit-image=0.22.0
  - xarray
  - dask
  - tqdm
  - holoviews
  - jupyter_bokeh
  - shapely
  - geojson
  - seaborn
  - rioxarray
  - ipython
  - memory_profiler
  - opencv
  - selenium
  - shap
  - gdal
  - dask-ml
  - pip
  - pip:
    - glcm-cupy
    - segmentation-models-pytorch